services:

  weather-api:

    build:
      context: .

    container_name:
      weather-api


    ports:
      - "9000:9000"


    volumes:

      - ./models:/app/models


    environment:

      PYTHONUNBUFFERED: "1"
      MODELS_DIR: "/app/models"


    restart:
      unless-stopped